# ==========================================
# 1. ENTRADAS (Inputs)
# ==========================================

# Escucha de NetFlow sintético
[[inputs.netflow]]
  service_address = "udp://:2055"

# Métricas básicas del sistema (CPU, RAM, Disco)
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.mem]]
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

# ==========================================
# 2. SALIDAS (Outputs)
# ==========================================

# A. Salida de Flujos hacia ClickHouse (Vía SQL Nativo)
[[outputs.sql]]
  driver = "clickhouse"
  data_source_name = "clickhouse://telegraf:admin123@127.0.0.1:9000/telemetria"
  namepass = ["netflow"]
  table_template = "netflow"

# B. Salida de Métricas de Sistema hacia VictoriaMetrics (Vía HTTP Prometheus)
[[outputs.http]]
  url = "http://127.0.0.1:8428/api/v1/import/prometheus"
  data_format = "prometheus"
  namedrop = ["netflow"]
