# Archivo de configuración principal de Telegraf

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = true
  quiet = false

# =====================================================================
# SECCIÓN DE SALIDAS (Hacia dónde enviamos los datos)
# =====================================================================

# 1. Salida a VictoriaMetrics (Métricas de salud del propio Telegraf y luego SNMP)
[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2

# 2. Salida a ClickHouse (Aquí enviaremos los flujos NetFlow más adelante)
# (Lo dejamos comentado por ahora hasta que configuremos la tabla SQL en ClickHouse)
 [[outputs.clickhouse]]
   address = "http://localhost:8123"
   database = "telemetria"
   table = "flujos_netflow"

# =====================================================================
# SECCIÓN DE ENTRADAS (De dónde recibimos los datos)
# =====================================================================

# 1. Monitorizar la salud del propio servidor (CPU, Memoria, Disco)
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.mem]]

# 2. Entrada de Flujos IPFIX/NetFlow (Escuchando en el puerto UDP 2055)
[[inputs.netflow]]
  service_address = "udp://:2055"
